version: '3'

services:
  server:
    image: node:16.9-buster
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports: 
      - "3000:3000"
    command: npm run dev
    # entrypoint: ["tail", "-f", "/dev/null"]